### ISSUE TITLE
fedpkg, not rhpkg, is used when on custom git branches

### ISSUE THREAD

**Issue by tserlin** [ktdreyer/rdopkg-tar#4]
I ran into a subtle error when running the "tar-changes" script for a ceph testfix.

If you're not on a regular ceph branch (e.g.: ceph-4.0-rhel-8), and using a testfix branch (e.g.: private-tserlin-ceph-4.0-rhel-8-*), the script assumes you want "fedpkg" and not "rhpkg":

https://github.com/ktdreyer/rdopkg-tar/blob/master/tar-changes#L157

When running it on RHEL 7, the "fedpkg upload" part failed because even though I did have fedpkg installed, it was trying to use a non-existent git option: `git remote get-url`.
Fedora's git has this option, but RHEL 7's git doesn't.

That said, the "tar-changes" did finish, and did create a dist-git commit OK, but it did not upload the *-changes tarball, nor did it update the "sources" file.

If you have an unconventional branch name, then the "osdist" function in rdopkg/guess.py will return "RDO".

**Comment by tserlin** [comment]
I created a separate branch as a workaround:

https://github.com/ktdreyer/rdopkg-tar/tree/private-tserlin-rhpkg-issue-4

**Comment by ktdreyer** [comment]
Looking at [the definition for `osdist()` upstream](https://github.com/softwarefactory-project/rdopkg/blob/0be8a8691e492126835d913b2ac3e303f1a63e95/rdopkg/guess.py#L290), I think that we want to drop the "private-foo-" suffix before the branch name, like `re.sub(r'^private-[^-]+-')`. What do you think @tserlin? Would that regex match all the branches that you use?

Looks like there's no test coverage for `rdopkg.guess.osdist()` [upstream in test_guess.py](https://github.com/softwarefactory-project/rdopkg/blob/173565f7f2b9ffa548b355a0cbc8f972f1445a50/tests/test_guess.py), so we should write a bunch of branch names to exercise all the cases we expect to use.

**Comment by tserlin** [comment]
Yes, "private-tserlin-" is pretty much what I only use for testfixes and hotfixes.

**Comment by ktdreyer** [comment]
I've refactored the rdopkg `guess.py` tests, added tests for `osdist()`, and added this feature.

https://softwarefactory-project.io/r/#/q/status:open+project:rdopkg+branch:master+topic:guess-improvements

**Comment by ktdreyer** [comment]
I've asked in #rdo (freenode) for someone to merge my changes above.

In the meantime, let's merge your changes that avoid `guess.osdist()` and `guess.new_sources()`.

**Comment by ktdreyer** [comment]
The fix is in rdopkg's master branch now, https://softwarefactory-project.io/r/18391

We need a new rdopkg release. I've requested this at https://github.com/softwarefactory-project/rdopkg/issues/186 and [the rdo dev list](https://lists.rdoproject.org/pipermail/dev/2020-August/009442.html).

**Comment by ktdreyer** [comment]
rdopkg 1.3.0 is in Fedora and EPEL 8. I think that means that we can close this.
